<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=US-ASCII">
    <title>Handle Exceptions that occur in Tasks</title>
    <link rel="stylesheet" type="text/css" href="./res/styles/normalize.css">
    <link rel="stylesheet" type="text/css" href="./res/styles/prettify.css" />
    <link rel="stylesheet" type="text/css" href="./res/styles/styles.css">
</head>

<body>
    <!-- Use the same title as the StartHere -->
    <header>Writing multithreaded mobile applications</header>

    <section id="main">

        <h1 id="page-title"></h1>

        <h2>Duration</h2>
        <p>10 minutes</p>

        <h2>Goals</h2>

        <p>
            The primary goal of this lab is to raise and catch exceptions that occur within a Task.
        </p>

        <div align="center"><img src="res/images/Ex3_complete.png" width="480" alt=""  style="border:1px solid #999999"/></div>
      
        <h2>Required assets</h2>
        <p>
            This exercise is a continuation of the previous exercise.  You may use your existing project or open the <b>Completed</b> solution in the <b>Exercise 2</b> folder.
            The provided <strong>Exercise 3</strong> folder contains a sub-folder named <strong>Completed</strong> with a solution you can use to check your work. Please make sure you have this folder before you begin.
        </p>

        <!-- Give them a challenge here, high-level steps of what we want them to do
             so they can use this instead of the step-by-step (baby steps) included below -->
        <h2>Challenge</h2>

        <p>

            <ol>
                <li>Throw an exception within the Tasks created in the <b>GenerateFractlAynsc</b> method and provide a custom message.  The message should include the managed thread ID, and the start and end rows of the data to be generated.</li>
                <li>Catch the Exception and display its message by awaiting the Task returned by <b>WhenAll</b> in a try/catch block.</li>
                <li>Retrieve the <code>AggregateException</code> from the task in the catch block, flatten the exception, and display all messages provided by the InnerExceptions property using <code>DisplayAlert</code>.</li>
            </ol>
        </p>

      
        <!-- Steps -->
        <h1>Steps</h1>
  
        <h2>Throw an exception within a Task</h2>
        <ol>
            <li>Open <b>MainPage.xaml.cs</b> and find the <b>GenerateFractlAsync</b> method.</li>
            <li>After the for loop completes within the <code>Task</code>, throw a new <code>Exception</code>.</li>
            <li> We'll pass some data back with the exception, create a string that includes the ID of the current managed thread, along with the start and end rows for the current partition.  Pass the string into the constructor of the <code>Exception</code>.</li>
            <li>Run the application, what happens?</li>
<p><a href="#" onclick="toggleCode(this,'GenerateFractlAsync');return false;" class="uiitem">Show Code</a>
<div class="indent-medium" id="GenerateFractlAsync" style="display:none;">
<pre class="prettyprint">
private async Task GenerateFractlAsync(int maxIterations, CancellationToken cancelToken)
{
    ...
    var tasks = PartitionRows(Environment.ProcessorCount)
        .Select(range => Task.Run(() =>
            {
                double startRow = row + (range.Item1 * increment);
                for (int y = range.Item1; y < range.Item2; y++)
                {
                    ...
                }

                throw new Exception(string.Format("{0}: rows {1} to {2}",
                    Environment.CurrentManagedThreadId, range.Item1, range.Item2));

            })).ToArray();
    ...
}
            
</pre>
</div>
</p>
        </ol>

        <h2>Catch the Exception raised in the Task</h2>
        <p>We raised an exception within our Task which went unhandled.  Notice that this failed silently but stopped our fractal from displaying.</p>
        <ol>
            <li>Before the call to <code>Task.WhenAll</code>, create a <code>Task</code> variable named <b>renderTask</b> and set it to <code>null</code>.</li>
            <li>Create a <b>try/catch</b> block.</li>
            <li>Within the <b>try</b> block, assign the result of the <code>Task.WhenAll(tasks)</code> to <b>renderTask</b>.</li>
            <li>Await <b>renderTask</b>.</li>
            <li>In the <b>catch</b> block, use <code>DisplayAlert</code> to show the message we sent with the exception.</li>
            <li>Run the application.</li>
            <p><a href="#" onclick="toggleCode(this,'Exception');return false;" class="uiitem">Show Code</a>
<div class="indent-medium" id="Exception" style="display:none;">
<pre class="prettyprint">
Task renderTask = null;
try
{
    renderTask = Task.WhenAll(tasks);
    await renderTask;

}
catch (Exception ex)
{
    await DisplayAlert("Render Data", ex.Message, "OK");
}
</pre>
</div>
</p>
        </ol>

        <h2>Handle Aggregate Exceptions</h2>
        <p>Although the code appears to working, notice that we're only getting one exception being raised regardless of the number of processors present.
            The iOS Simulator for example will report the same number of logical processors as the system its running on.</p>
        <ol>
            <li>Change the <b>catch</b> statement to its simple variant.  Delete <code>(Exception ex)</code>.</li>
            <li>Delete the call to <code>DisplayAlert</code> within the <b>catch</b> block.</li>
            <li>Save the <code>AggregateException</code> exposed on <b>renderTask</b>'s <code>Exception</code> property to a local variable named <b>aex</b>.</li>
            <li>Use the <code>Flatten</code> method on <b>aex</b> to create a new <code>AggregateException</code> without any child <code>AggregateExceptions</code>.</li>
            <li>Use <b>DisplayAlert</b> to display the messages from all the exceptions within the flattened <b>aex</b>.  The exceptions are exposed as a <code>ReadOnlyCollection</code> on the <b>InnerExceptions</b> property.</li>
            <li>Run the application.  Notice the alert is now showing the exception message from each Task. </li>
<p><a href="#" onclick="toggleCode(this,'InnerExceptions');return false;" class="uiitem">Show Code</a>
<div class="indent-medium" id="InnerExceptions" style="display:none;">
<pre class="prettyprint">
catch 
{
    AggregateException aex = renderTask.Exception;

    if (aex != null) 
    {
        string message = string.Join(Environment.NewLine, 
            aex.Flatten().InnerExceptions.Select(x => x.Message));

        await DisplayAlert("Render Data", message, "OK");
    }
}
</pre>
</div>
</p>
        </ol>

        <h1>Summary</h1>
        <p>
            In this exercise you caught and read data from exceptions raised within a Task.
        </p>
        <div class="align-right">
            <a href="../Start%20Here.html">Go Back</a>
        </div>
    </section>

    <script src="./res/js/jquery.min.js"></script>
    <script src="./res/js/prettify.js"></script>
    <script src="./res/js/script.js"></script>

    <footer>Copyright (C) 2018 Xamarin Inc., Microsoft.</footer>
</body>
</html>
